try {
	${2}
} catch	{
	case ${1:Exception} => ${3}
}
